---
# Elasticsearch Ansible Playbook
- hosts: all
  remote_user: '{{ user }}'
  become: yes
  #become_user: '{{ user }}'
  become_method: 'sudo'
  #remote_user: 'ubuntu'
  #sudo: yes

  vars_files:
    - defaults/main.yml
    # - vars/vagrant.yml

  tasks:
    - include: tasks/main.yml
    # Uncomment to install and enable SPM. Make sure to set the spm_client_token variable in your inventory.ini to your SPM key
    # - include: tasks/spm.yml

  handlers:
    - include: handlers/main.yml
